class UnipredCore:
    def __init__(self, config: str) -> None: ...
    def login(self, email: str, password: str) -> None: ...
    def login_apikey(self, key_id: str, private_key_path: str) -> None: ...
    def _fetch_markets_bytes(
        self,
        exchange: str | None = None,
        limit: int = 100,
        cursor: str | None = None,
        status: str | None = None,
    ) -> bytes: ...
    def _get_quote_bytes(self, ticker: str, exchange: str | None = None) -> bytes: ...
    def ingest_all(
        self,
        db_path: str,
        lancedb_path: str,
        exchanges: list[str] | None = None,
        statuses: list[str] | None = None,
        test_mode: bool = False,
    ) -> None: ...

class PyLanceDb:
    @staticmethod
    def connect(uri: str) -> PyLanceDb: ...
    def add_markets(self, markets: list[object]) -> None: ...
    def create_index(self) -> None: ...
    def search(
        self, query_vector: list[float], limit: int
    ) -> list[tuple[str, str, str, str, str, str]]: ...