class UnipredCore:
    def __init__(self, config: str) -> None: ...
    def login(self, email: str, password: str) -> None: ...
    def login_apikey(self, key_id: str, private_key_path: str) -> None: ...
    def fetch_kalshi_markets(
        self,
        limit: int = 100,
        cursor: str | None = None,
        status: str | None = None,
        min_close_ts: int | None = None,
        max_close_ts: int | None = None,
    ) -> str: ...
    def get_quote(self, ticker: str) -> str: ...